name: Daily Update

on:
  schedule:
    - cron:  '49 4 * * *'
  workflow_dispatch:


jobs:
  daily-update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: pwsh job_scripts/daily-score-pull.ps1
    - run: git config --global user.email "stats-bot@arbitrarydata.co.uk" && git config --global user.name "stats-bot"
    - run: git add .
    - run: git commit -m 'Automated daily stats update.'
    - run: git push -o ci.skip
