name: send-email

on:
  push:
    branches: [ master ]

jobs:
  send-email:
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: eu-west-2
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      S3_BUCKET_URL: ${{ secrets.S3_BUCKET_URL }}
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
      MAILERSEND_API_KEY: ${{ secrets.S3_BUCKET_NAME }}
      # Player email addresses.
      Vaalkor_EMAIL: ${{ secrets.VAALKOR_EMAIL }}
      IC_HEDGIE_EMAIL: ${{ secrets.IC_HEDGIE_EMAIL }}
      Mordis_EMAIL: ${{ secrets.MORDIS_EMAIL }}
      Sibuan_EMAIL: ${{ secrets.SIBUAN_EMAIL }}
      Tremarctinae_EMAIL: ${{ secrets.TREMARCTINAE_EMAIL }}
    steps:
    - uses: actions/checkout@v2
    - run: pwsh ./send-email.ps1
