name: send-email

on:
  push:
    branches: [ master ]

jobs:
  send-email:
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: eu-west-2
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      S3_BUCKET_URL: ${{ secrets.S3_BUCKET_URL }}
    steps:
    - uses: actions/checkout@v2
    - run: pwsh ./send-email.ps1 
