name: Update

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: echo bollocks > test.txt
    - run: git status
    - run: git add .
    - run: git commit -m 'testing git push!'
    - run: git push -o ci.skip
